using System;
using System.Collections.Generic;
using System.Text;

namespace HelperStructures
{
    public enum ErrorCode { SUCCESS, NULL_ARGUMENT, ACCESS_DENIED, ALREADY_CONNECTED, ALREADY_STARTED, CONNECTION_ABORTED, CONNECTION_REFUSED, INVALID_ARGUMENT, NETWORK_UNREACHABLE, NOT_CONNECTED, OPERATION_ABORTED, OPERATION_NOT_SUPPORTED, TIMED_OUT };

}
